// Auto-generated by `npm run robinhood:sync`. Do not edit by hand.
// Source: https://robinhoodchain.blockscout.com/api/v2/tokens/
//
// Logo URLs only. Lower priority than the RHJ asset data, so this mainly
// supplies icons for non-equity tokens added via tokens/manual.ts.

import { TokenInfo } from '@uniswap/token-lists'

const assets: Record<string, Partial<TokenInfo>> = {
  '0x01397109534e47d3742e794D3a610fA1C3158888': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174660/small/nfe2qfplxrnvi92bl7fz9tctq2na.?1784446869',
  },
  '0x01637b14B7378B99dE75A64d50656d98488D9a4d': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174281/small/marian.jpg?1783654680',
  },
  '0x0172fD20b8E89CB577a6EDd3B800EE7b2a5B00c1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174484/small/xokvrd9f7d2p72j4ahfhshxmv31x.?1783767319',
  },
  '0x0188DA44dCc9b6C9D0d80DE904c633c5ff227777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174636/small/givest.jpg?1784293859',
  },
  '0x020bfC650A365f8BB26819deAAbF3E21291018b4': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174280/small/cashcat-logo.jpg?1782922765',
  },
  '0x02cf91De4E80d3dd104E5ad6FC23EB15A9B6f8e2': {
    logoURI: 'https://plebindex.com/icon.png',
  },
  '0x05b37Fb53A299a1b874A619e1c4C404D52C36F4C': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x05b37fb53a299a1b874a619e1c4c404d52c36f4c.png',
  },
  '0x05E4EDA215FA3DA3d540d8dd381e893E9daAC15F': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175282/small/200.png?1786069198',
  },
  '0x05E6eAe62791c92B66D2851c288Cf51b8d4Ca383': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175381/small/Icon.jpeg?1786207511',
  },
  '0x0684e19528cCfD570fb00f0Ca626Dac4bdab17cf': {
    logoURI:
      'https://pbs.twimg.com/profile_images/2074894993752576000/LAxx6AsP_400x400.jpg',
  },
  '0x0762C1708F0D23F86b29D6B857121FF7DF357506': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175241/small/notawebsite.jpg?1785896695',
  },
  '0x0830A9Dd26a04e959657AB6788d45f5725590c32': {
    logoURI:
      'https://assets.coingecko.com/coins/images/34515/small/android-chrome-512x512.png?1706198225',
  },
  '0x0856F71C65268DA154DA4413d961cb348Dc6119d': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174321/small/magnific_l7br5G4gv9.png?1783181131',
  },
  '0x09fD8577a5d4A7202d41aa3040F4247dF4eA2D98': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175323/small/flamingo.jpg?1786095216',
  },
  '0x0aCb834130D284BFfFa1C697f02DDDaFd8F50335': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174556/small/oi0m02s0jssx77gheb2wpn2v11q6.?1784016046',
  },
  '0x0AF77e27F535256965944E617a386570f5C0432a': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174675/small/mylaw7bl6fl5k8x3bonq2arqg9ho.?1784553143',
  },
  '0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73': {
    logoURI:
      'https://assets.coingecko.com/coins/images/2518/small/weth.png?1696503332',
  },
  '0x0c1eD62D7811e5b437e537Ac9d0592469C119C74': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174794/small/pg5adkfrjm0a1p8j41q5dg1ez8hu.?1784882493',
  },
  '0x0C3260aF4B8f13a69c4c2dFb84fD667890CDFa14': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x0c3260af4b8f13a69c4c2dfb84fd667890cdfa14.png',
  },
  '0x0E6e67Ba88e7b5d9B67636A215c76779B948dE79': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x0e6e67ba88e7b5d9b67636a215c76779b948de79.png',
  },
  '0x0e8720B8cD84F95b4b6696adbFA8063c4B8B94F2': {
    logoURI: 'https://www.hoodbuybutton.com/logo.png',
  },
  '0x0f17206447090e464C277571124dD2688E48AEA9': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x0f17206447090e464c277571124dd2688e48aea9.png',
  },
  '0x0f68BEE9880a41CDf9713C24358FfDB4756d53c2': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175274/small/skrimp.webp?1786026864',
  },
  '0x10dc3d3719b507e6bF3fC90c3D327d8590827777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174757/small/Untitled_design_%2861%29.png?1784795241',
  },
  '0x117cc2133c37B721F49dE2A7a74833232B3B4C0C': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x117cc2133c37b721f49de2a7a74833232b3b4c0c.png',
  },
  '0x12f190a9F9d7D37a250758b26824B97CE941bF54': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x12f190a9f9d7d37a250758b26824b97ce941bf54.png',
  },
  '0x156E175DD063a8cE274C50654eF40e0032b3fbcF': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x156e175dd063a8ce274c50654ef40e0032b3fbcf.png',
  },
  '0x15Cd20759CE7F3285c29A319dE2D1A2e098c6f43': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x15cd20759ce7f3285c29a319de2d1a2e098c6f43.png',
  },
  '0x164D9da79722c5294369e79807980E0Bff257777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174676/small/vkoksjd43j74j4x3jxva13yl9k4l.?1784553272',
  },
  '0x1755C2910c126eE1b0CF1E08a307Dc9E787285a0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/13469/small/1inch-logo.jpeg?1759404663',
  },
  '0x178E54df3D091EE4D0B2534742eF9e3692b76526': {
    logoURI:
      'https://assets.coingecko.com/coins/images/52626/small/bankr-static.png?1736405365',
  },
  '0x17bb0C898254406b1Ea2e8E99B0C263e26c9E4a4': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174285/small/DIH_PFP.png?1784475558',
  },
  '0x18E674231A58c239Dc7DaeDcffE15Ec3A24cff5c': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175265/small/hookr.jpg?1786013509',
  },
  '0x19F862c0cf83a9F65b19C37Fd1F4fd5bAcB097ae': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174893/small/cooper.jpg?1785394388',
  },
  '0x1aBf16f660CCbAa22CE8646deB1B63635D582228': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174658/small/fonz.jpg?1784446665',
  },
  '0x1AF6446f07eb1d97c546AFC8c9544cBDF3AD5137': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x1af6446f07eb1d97c546afc8c9544cbdf3ad5137.png',
  },
  '0x1b0E319c6A659F002271B69dB8A7df2F911c153E': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x1b0e319c6a659f002271b69db8a7df2f911c153e.png',
  },
  '0x1Cdad396DB64BDa184d5182A97Dd9B3C62100b7D': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x1cdad396db64bda184d5182a97dd9b3c62100b7d.png',
  },
  '0x1dAe71A215eE5C696cb644F030597AE4F32831C0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174428/small/sparkleware.jpg?1783669849',
  },
  '0x1dF1F09c4Dd65C76746d53467361D536cDfDC719': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175321/small/xm09917bz85kwtx4ee6qz2omzs2m.?1786094902',
  },
  '0x1e0AAaf3FdB5C0de3574d215e7081177Ec0F96a3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/34235/small/AiPin-200px.png?1704306335',
  },
  '0x20024E485c0B22b42855589700721b28320A7777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175383/small/IMG_1143.jpeg?1786208540',
  },
  '0x2076CD26D8Cf26f91655d4Ada3dD2fdBFdd8e7a4': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174803/small/apes.jpg?1784969088',
  },
  '0x20Aa6E63076EE856F46bb31f7D30E60B335B11E9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174736/small/c2or6npzh6yqz16sjhjkj7dyng57.?1784704179',
  },
  '0x2103faA9D1762e27a716C61718b3aCf3Ec1F9bf1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174509/small/rhood.jpg?1783842242',
  },
  '0x218EEc7d0C6A26bA119063B3228B8D04085545D3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174521/small/20w3ifjdw0gefoczkwnh7ztvy99e.?1783855266',
  },
  '0x21Ed792De0Ebfa85c2f55FF45b2241C576727f7B': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175371/small/divine.jpg?1786158620',
  },
  '0x230442C8133A9efb4c278b3723043444749Ca08b': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174861/small/IMG_0924.jpeg?1785208862',
  },
  '0x232CDFc415D10b673845D83Dc02ba2eaBe7e30d1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174859/small/CoinGecko_Logo_200x200.png?1785157954',
  },
  '0x2355431b83B1A8E40172D099d90243D8D666b56B': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174456/small/uu5c80xhybczyk1te0r9tnl31eto.?1783692760',
  },
  '0x23f88eda2B24A0D45d4C3e2AD05edFf30f860697': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174558/small/leavehood_400x400.jpg?1784019212',
  },
  '0x241F3Caad03Db31137F641beF005A32176530024': {
    logoURI:
      'https://assets.coingecko.com/coins/images/31193/small/NPC_200x200.png?1696530021',
  },
  '0x25824447ED0E26B0741858b67065bB6BD0017B15': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174422/small/mdt1lm9nr0btuf6esxag7sjf55bd.?1783668507',
  },
  '0x25C288E6D899b9BC30160965aD9644c67e73bE0C': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x25c288e6d899b9bc30160965ad9644c67e73be0c.png',
  },
  '0x26C41B10527DE2Dc870fa5C9D5f4A8dBAA966cDf': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174577/small/zue9xia7wlzsab8hj66uebykzxqy.?1784095461',
  },
  '0x26c7121e41e779327Adbd5682646dC5deb764539': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174390/small/app-icon-200x200.png?1783578375',
  },
  '0x27c99fBde9D0d2AA4f4Bfb4943f237843DdF6958': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x27c99fbde9d0d2aa4f4bfb4943f237843ddf6958.png',
  },
  '0x281079a7832B15238Ed9C6eC1e787f3Ed9DB6AD1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174398/small/hoodies.jpg?1783580769',
  },
  '0x282e87451E10fA6679BC7D76C69BE44cD3fC777C': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x282e87451e10fa6679bc7d76c69be44cd3fc777c.png',
  },
  '0x284358abc07F9359f19f4b5b4aC91901Be2597Ba': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x284358abc07f9359f19f4b5b4ac91901be2597ba.png',
  },
  '0x29fbaa3668E688C83fae9b5Dd13cC3CfC097ccBF': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174877/small/dahood.jpg?1785289998',
  },
  '0x2b10D89bA75cfE18f2678a66e4c18c1005b03AFA': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174662/small/h2nhpetu0yhvn5vh8pgm7aps9g00.?1784447187',
  },
  '0x2C1eE949a32052cb372b736D4af00A9F2b9335c4': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174847/small/photo_2026-07-25_18.57.17.png?1785085279',
  },
  '0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x2e0847e8910a9732eb3fb1bb4b70a580adad4fe3.png',
  },
  '0x2e9c3B1C6E7703D1784b2B8F80ef4e99D76b3E56': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174452/small/wa6a1q8ciuo4j2rtsmxmfpw3y4w2.?1783691743',
  },
  '0x2Ea05472e1b7289004e5A1F6D959f6F2F3a6fecB': {
    logoURI:
      'https://assets.coingecko.com/coins/images/31482/small/photo_2023-08-25_07-54-16.jpg?1696530294',
  },
  '0x3018E275Da8D1acD16E7B803e74FcA9c251fd60f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174540/small/7wyw5t1rcw7ekj6piizniljhlipi.?1783957311',
  },
  '0x30C9c51E06faA8cc71e4C101a69a9ed8d01EE91a': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174790/small/pfo9mtgvg4iad4f3x6b8zt008xpp.?1784880477',
  },
  '0x319B6aef5191b5a8FeD772f2d1482831FAbB1a58': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175315/small/pawsinu.png?1786088347',
  },
  '0x31BE8f7485e36928C9De86566c62da82d4B6BF81': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174476/small/vlad.png?1783762041',
  },
  '0x31EF2F4e678b3640A380C5882ae1A73763D138E9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174679/small/mv6er40qzfjeicirabn4e07yvxu3.?1784554561',
  },
  '0x322F0929c4625eD5bAd873c95208D54E1c003b2d': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x322f0929c4625ed5bad873c95208d54e1c003b2d.png',
  },
  '0x32758ae8e02B0A2CB6b802B6aAEaF74158C169F7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174511/small/xgv1bpooulvjh0ug2ssfqjgsluww.?1783848672',
  },
  '0x343a9C531AcF28c4d9f4cd8Ef2d6413CEBa3c2df': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174539/small/goxx_400x400.jpg?1783957268',
  },
  '0x3450598e419aBB5609f60e4B2Fda127ff0897777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174616/small/aibd7en0i4lmsrgjvibo397y3up5.?1784192160',
  },
  '0x3542c7008C4Ee360e7484a910B09af86b237b062': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175279/small/feeles.webp?1786027993',
  },
  '0x36046893810a7E7fCE501229d57dc3FC8c8716d0': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x36046893810a7e7fce501229d57dc3fc8c8716d0.png',
  },
  '0x364D9F23ede3aDA0F5e3f41DF10f0a0D01C57777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174688/small/logo_quiver.jpg?1784627094',
  },
  '0x3746a5ebCA295Dee695dd1bcba50A8626Df3099C': {
    logoURI: 'https://humanoidnetwork-docs.pages.dev/assets/favicon-48.png',
  },
  '0x385b36Ff682Ab4C76E7c37A66b96aABC466471d5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175260/small/pools.png?1786007584',
  },
  '0x38a22A55FE0bb97428D1f145Bc8BD0E2d4f12E2c': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175237/small/ni4j0z2ky0qwi2pfj40ylw87s48f.?1785895010',
  },
  '0x38bb87Cf3E7344A82be7CD671c191f015b97eEe6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174554/small/30768.png?1784014852',
  },
  '0x39dBED3a2bd333467115dE45665cC57F813C4571': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174571/small/jhitvkisdq8fhxvimdkpcw7y3dx5.?1784093932',
  },
  '0x39EC44Bee4F6A116c6F9B8De566848a985C53C60': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x39ec44bee4f6a116c6f9b8de566848a985c53c60.png',
  },
  '0x3AaA874b93612bF3f683b85e2739e81eaB38321e': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174508/small/coco.jpg?1783840381',
  },
  '0x3aE3faCC99F43D5A39254A0b9f5cc0291ECd39cc': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174901/small/nvemzju9ekgltivvyj0oru6yypdw.?1785396299',
  },
  '0x3b14C39E89D60D627b42a1A4CA45b5bb45Fc12e2': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x3b14c39e89d60d627b42a1a4ca45b5bb45fc12e2.png',
  },
  '0x3D0a2e4763EeE58a7c631ACF7fF13Ad6398A5141': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174541/small/cqbodpv9mzuntm480qba1of6y74z.?1783957424',
  },
  '0x3F5e952b29bE5D70846FC2bA472BeA05761A769E': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174485/small/IMG_2485.jpeg?1784083180',
  },
  '0x3F9f0b6073Ee8c495Aed96869AF31850fED40FeB': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174900/small/3hi8m11pdx5a118am4mfhgk8s9jr.?1785396206',
  },
  '0x407470F85e0b342a52AaE2F191E135cEF2947777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174605/small/n7xy2tqh7j0xj15pp1e738ayr1wi.?1784190421',
  },
  '0x40858070814a57FdF33a613ae84fE0a8b4a874f7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174289/small/syrupUSDG.png?1783055974',
  },
  '0x408c14038a04f7bD235329E26d2bf569ee20e250': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x408c14038a04f7bd235329e26d2bf569ee20e250.png',
  },
  '0x40e836F547653691B74C0d68fFf60beFE36CB024': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174734/small/517bpw2jczl05x5sldy4dk1k4we1.?1784703805',
  },
  '0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x411efb0e7f985935daec3d4c3ebaea0d0ad7d89f.png',
  },
  '0x4189F0c66EBBB0bfeF1C31f763131361EF32f77C': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x4189f0c66ebbb0bfef1c31f763131361ef32f77c.png',
  },
  '0x41Dc5ed850E67318C3B3f1DFDF833B27a8Bd17b5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175193/small/hood_logo.jpg?1785475469',
  },
  '0x41F41F7B849A25e027876c485544c8088f447A11': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102172993/small/axtt4lvrtgids5t0emi1p56igs49.?1777044509',
  },
  '0x43E7Cb9984aD95aA808ac21998cc8D5f909e47aF': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174614/small/vsy51l1nd423o96w8w1eoems5xwg.?1784191746',
  },
  '0x43eeA882B845a8493152Ebc55cF30aE9281b02d5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174789/small/FIRE.png?1784876296',
  },
  '0x44c4F142009036cF477eD2d09932051843137CF1': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x44c4f142009036cf477ed2d09932051843137cf1.png',
  },
  '0x45242320DBB855EeA8Fd36804C6487E10E97FCF9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174418/small/x1o0qj8dm7mlay3licerc1y75hr4.?1783667012',
  },
  '0x46cf2cA61505902a4410B3B4242d787cD4737777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174494/small/e7224c1c-0a5c-4652-909b-b167c498c2f2.png?1783781659',
  },
  '0x47eE684E52e5d92De0B24D4E00aD45c7Af7Db9A3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174531/small/HoodDomains.png?1783930998',
  },
  '0x47F93d52cBeC7C6D2CfC080e154002370a60dAEA': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x47f93d52cbec7c6d2cfc080e154002370a60daea.png',
  },
  '0x48961813349333209994750ffA89b3c5C22eC969': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x48961813349333209994750ffa89b3c5c22ec969.png',
  },
  '0x499dC58539BA6869EE15b6c2a3c3c07F1AC4995F': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174796/small/3tvdoflf3n1rq7rsyubuav9pbzja.?1784883304',
  },
  '0x49a947189125330f1658C65cE30882956Bc9DbDA': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174747/small/pbypw4chpzm2wqsd57xcrn8dlbzj.?1784782488',
  },
  '0x49aE2b07541943879fD17f72965DE24Ee066357b': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175332/small/stnk.webp?1786097634',
  },
  '0x49bac47750F3dCdBa49350B5D74fd399e90f97C6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175420/small/The_Bull.jpg?1786296896',
  },
  '0x49D8022cfa113DaDb8cb1A5b22250524cf24B926': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175377/small/Boyz_N_The_Hood.png?1786203382',
  },
  '0x49e34dBB35023D51F981558F54e5523FA9C44b03': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174896/small/8rv4nyi30qd54lsxatr8a0i46hgy.?1785394913',
  },
  '0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x4a0e65a3eccec6dbe60ae065f2e7bb85fae35eea.png',
  },
  '0x4a6Eec8A30b49d289B9Fc865Fd374b4D61eab8fB': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175213/small/liluni-pfp.png?1785613331',
  },
  '0x4C9D9527c4E3Cf9FAF70f0df8429d2ccED157492': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174462/small/dumb.jpg?1783694383',
  },
  '0x4D21483a44Bf67a86b77E3dA301411880797D452': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x4d21483a44bf67a86b77e3da301411880797d452.png',
  },
  '0x4e62068525Ab11FE768e29dfD00ef909B9803016': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x4e62068525ab11fe768e29dfd00ef909b9803016.png',
  },
  '0x4EA005168D7F09a7A0Ba9D1DEf21a479950E44C2': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x4ea005168d7f09a7a0ba9d1def21a479950e44c2.png',
  },
  '0x4F0d7ea112547Af5dAD59959d98B6A8ee3355Bcc': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174891/small/cryingcat.png?1785394016',
  },
  '0x4f298B7B07abcB81e4c097C28dFE68D49F17c0de': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174839/small/hp.jpg?1785055281',
  },
  '0x516c0878acca15E7eB2f6a401b5B6cd2a0f9f455': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174560/small/30puty0mmko4uqgh1o0gj4ly6k52.?1784019561',
  },
  '0x51b57D1157975756C156EE28E3E167718792B665': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174578/small/pquwcujemzityddphqqfmpht38qj.?1784095577',
  },
  '0x51Fb76BE80ab6daAa345D818f4E06441816b4fEa': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175256/small/nasdanq.png?1786000485',
  },
  '0x521Cf887E6531c6F667b5BC4D896E5d9bfE8EB2E': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x521cf887e6531c6f667b5bc4d896e5d9bfe8eb2e.png',
  },
  '0x5266eeafF092D6136AB63D18B975A60a0Cc0C8f7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174414/small/RHPEPE.png?1783651521',
  },
  '0x53d2e1225AaCe4551194eCBB6bbE5c44d94AA5fa': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174376/small/robinhood.png?1783488235',
  },
  '0x556f6D981eeb12454691e6BA6e1E2e1D5B9F6bA7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174856/small/kittycoin_400x400.jpg?1785148049',
  },
  '0x55796b27Aa48444Fa2cAEF2BF902E12E9c280Dc9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174347/small/robin_400x400.jpg?1783360662',
  },
  '0x558378E000D634A36593E338eBacdd6207640EfE': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x558378e000d634a36593e338ebacdd6207640efe.png',
  },
  '0x5599b56bc8d1c7c87a05b6ef5F903997a8c1e8dC': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175322/small/keel.webp?1786094940',
  },
  '0x56910D4409F3a0C78C64DD8D0545FF0705389870': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174740/small/qffiSdBd_400x400_%281%29.jpg?1784708104',
  },
  '0x56A98Db16Cf501b686c14BA00a5DeC02E87083FA': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174348/small/robinfun_400x400.jpg?1783360807',
  },
  '0x56d23beE5f41A7120170b0c603Dae30128e460e9': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x56d23bee5f41a7120170b0c603dae30128e460e9.png',
  },
  '0x5788116f4Fe1820bf499C26FC7203630BF2d020f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174580/small/HM.jpg?1784096041',
  },
  '0x57a1AB439e8C24B90Ecc6534C05621d6E68ED35A': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174416/small/6fwxi1r56qpfm18h87bp83rravj4.?1783666583',
  },
  '0x57C0E45cB534413D1C20A4240955d6bB250BB4F1': {
    logoURI: 'https://up33.xyz/up-mark-tile.svg',
  },
  '0x58d0d7FDB00855DffFb387481B115bAF6BA28127': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174798/small/ijmh7gnx6b0c9t19h77un5oiiq42.?1784883727',
  },
  '0x58FfE4a942d3885bAa22D7520691F611EF09e7AA': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x58ffe4a942d3885baa22d7520691f611ef09e7aa.png',
  },
  '0x59818904ab4cE163b3cE4FfB64f2D6Ca02c434B4': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x59818904ab4ce163b3ce4ffb64f2d6ca02c434b4.png',
  },
  '0x5AB5f320D8a3dE4967fBED6D0678Ad71683f53c7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175278/small/trash.jpg?1786027872',
  },
  '0x5ae8D07763d74ca5Bd22f8a5b26C6d953E61DFe2': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175313/small/froglet.png?1786087540',
  },
  '0x5B58e24034bc052aF010d6E863ae81ACDE261b1d': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174709/small/nkzuwz0gym2qzde0pdqoqowbzgdw.?1784645654',
  },
  '0x5bd252b4D7AA573813D1c6A4888f778790583667': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174459/small/stock.jpg?1783694761',
  },
  '0x5c0033cE0029f709A51313E20615f74E1D00a549': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175255/small/prs2nxq2j9y3kmnqrzb7n57kb4qv.?1786000135',
  },
  '0x5c90450Bbb4273D7b2f17CF6917AEB237A569679': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x5c90450bbb4273d7b2f17cf6917aeb237a569679.png',
  },
  '0x5Cb6F181081301b44905F3ae15419112ecaBd8A6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174876/small/pipedog.png?1785289835',
  },
  '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34': {
    logoURI:
      'https://assets.coingecko.com/coins/images/33613/small/usde.png?1733810059',
  },
  '0x5d6Fa71583E40d6a40AB09Cd071F24F6603b0970': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174617/small/ezu124eudmkdr6p6i29d24bhm8na.?1784192278',
  },
  '0x5E453647539D4DD766D7C4c3D6CE589900D39415': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175379/small/IMG_1105.jpeg?1786204256',
  },
  '0x5e81213613b6B86EaB4c6c50d718d34359459786': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x5e81213613b6b86eab4c6c50d718d34359459786.png',
  },
  '0x5Edb417509a869b1D8222dEa05257B8c8Ba00361': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175407/small/DTF.png?1786293495',
  },
  '0x5f10A1C971B69e47e059e1dC91901B59b3fB49C3': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x5f10a1c971b69e47e059e1dc91901b59b3fb49c3.png',
  },
  '0x5f18b02B8320Ef1C5B7d7a5A8BAd482a767f4716': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174579/small/bp1i40cgq9ngr00cq6tof389kkwo.?1784095672',
  },
  '0x5f62C57e5C537887117EeF828b7E3Ad41C009FEb': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175335/small/18gdk5mcz4mnl22tn494qzj9iuoi.?1786102824',
  },
  '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168': {
    logoURI:
      'https://assets.coingecko.com/coins/images/51281/standard/GDN_USDG_Token_200x200.png?1730484111',
  },
  '0x601FdA468bdd8096067DFC1C86654Ce2D8D7Ab03': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174885/small/4JQs6irI_400x400.jpg?1785334461',
  },
  '0x6245e67affA44a23077f0Ea7f981a8DC743a0c47': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175259/small/frong.png?1786003344',
  },
  '0x62C71cd34a52c30d894419CBcc55Db2aFA8032eA': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174641/small/fzvhldxmvphx85ls235mclk6bf3x.?1784363718',
  },
  '0x62fd0668e10D8B72339BE2DCF7643001688ff13B': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x62fd0668e10d8b72339be2dcf7643001688ff13b.png',
  },
  '0x6330D8C3178a418788dF01a47479c0ce7CCF450b': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x6330d8c3178a418788df01a47479c0ce7ccf450b.png',
  },
  '0x636358c682843ca3976b32cb4dd5FB13fB407777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174621/small/IMG_2615.jpeg?1784257687',
  },
  '0x6365Fd27DdEfC42f50895994B67b04fab5f08D5e': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174530/small/1.png?1783910785',
  },
  '0x63e0ca3841Bff47A191949417aB64F82CFA3314B': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174488/small/ohrrr5da9yotw3m90pqmyixxwt32.?1783768224',
  },
  '0x64459A5592723ffBaceAff5799f4a9EdAc579C6c': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174785/small/hooja.jpg?1784870836',
  },
  '0x647dD517c8820fc9874E1a3f58E6e0b9A43395c0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174725/small/0mtztu1maia5evtmsnt799el5mc1.?1784701910',
  },
  '0x64abFc878dC340bBf33BaE4AAf39ed33Fb1828c0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174424/small/am3nerfpw2jwpo8mv5j76o23a88e.?1783668870',
  },
  '0x6543B7746ca744C4bb2198191E71f40FF04C41b9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175206/small/o5h617j9136bygr7xlok96lggtrp.?1785573883',
  },
  '0x658bF542C9384dC000A07540B0B29Ef7E79fe126': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175261/small/pos.jpg?1786007920',
  },
  '0x65b445518B1AD0d9C597731494f5bD2991b7EC08': {
    logoURI: 'https://clawbank.co/clawbank-token-icon-48.png',
  },
  '0x667f0926022E6B9e9F67A9314eD5830bE54346b2': {
    logoURI:
      'https://assets.coingecko.com/coins/images/50377/small/flay.jpg?1727401416',
  },
  '0x6689aB375AaaA9Aed78aAABa2e8edcC547478Cf1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174631/small/2p7e3dmb8tyansb5nog13y66iprp.?1784289458',
  },
  '0x66CEF844f82a461444621F1fCb53efA9ed6DeE18': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174495/small/photo_2026-07-02_22-21-50.jpg?1783781931',
  },
  '0x684618c70480A70637692A51A3a9398DFd7ab0f5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174801/small/gtr.jpg?1784967973',
  },
  '0x692dCCa648e2E26baAf9Da4aebF7cDd5Ac2171D5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174735/small/fua1doc7gw0w2dhy9zwzr9wcubpf.?1784704012',
  },
  '0x69984Ad3322300039f2855f81C44Dbc532EFe744': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174838/small/tygr.png?1785054652',
  },
  '0x6A4BaA1927F37256017342DBD8FEc0c12831B8e3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174633/small/45zcyi730ho6otaw4fbz9ctaoac1.?1784293501',
  },
  '0x6E7e0dB14D23144ef3e78d3294aA408aC38427b8': {
    logoURI:
      'https://raw.githubusercontent.com/ashton-bleeep/bleeep_public/main/brand/logo-256.png',
  },
  '0x6e9aCBFbdD8b57649ffeAcEa4D26A81aE1395367': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175264/small/goat.webp?1786009007',
  },
  '0x6eDA83Fc299C10d474068A7E69771c809Bcbbba3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174570/small/b6b5ojnnrpnx7zs0zm302gumiizv.?1784093688',
  },
  '0x7168563B0E70124f0C7c0cF2F13a8D1861BAf4A5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174659/small/zpo16kazej461buko6zozopkfqdc.?1784446814',
  },
  '0x727701F88f09Fed71eb217Bcea88b3F314CF7079': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174630/small/41nxlf8zihm0bizumu35snw3bls9.?1784288993',
  },
  '0x729BCB002e38f415502596617Cd52321aCb4e681': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174726/small/qjwrmt07glcxhrmn0xfnus0fjpvo.?1784702013',
  },
  '0x7331991062f3B1E4eb0FD0506bF1ff0779e08b91': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174684/small/200x200_TransparentBG_Mascot.png?1784612370',
  },
  '0x745C1C97551204F10cd5Eb51c1B6902FeCe13b0E': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174527/small/2026-07-11_20.22.21.jpg?1783871033',
  },
  '0x7541872e32Bb529d7FF11D6C59832269ce33a6FF': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174615/small/wi15njncifod4ctl8i083ewe9xmr.?1784191969',
  },
  '0x75742c18BC1f1C5c5f448f4C9D9C6F66dafAAa38': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x75742c18bc1f1c5c5f448f4c9d9c6f66dafaaa38.png',
  },
  '0x75C8258eAa6d0f94b82951194191cA3efB0bCBe2': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174516/small/5kybcmg7gseqm1pakwwam51t2u70.?1783850995',
  },
  '0x75ecb5F2BFdE7F8C3258511dC0996f10d5C88B8b': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175370/small/horn.jpeg?1786158323',
  },
  '0x76761d4aEE1e7D6b2B8DEdbd13925d6C220b0725': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175295/small/logo.jpg?1786074528',
  },
  '0x77581054581B9c525E7dd7a0155DE43867532d03': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174392/small/wishbone.png?1783579749',
  },
  '0x7817C85e4390Bc83A58A47A71f0A5FA83a4e16D4': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174553/small/LOGO.JPG?1784014807',
  },
  '0x79D2234Ed4Ee24880835F261DF9A98FcEfC7600e': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174284/small/the-hood.jpg?1782938983',
  },
  '0x7c04E6A3368F2A1DE3874f0e80d2e0A1a9915da6': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x7c04e6a3368f2a1de3874f0e80d2e0a1a9915da6.png',
  },
  '0x7dc013eB55e436f30d7ED1AFE4E36d6e45e3c3f7': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x7dc013eb55e436f30d7ed1afe4e36d6e45e3c3f7.png',
  },
  '0x7e86381A763F0Ecca2bDF27C54eAC403ddD48123': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174374/small/70586C54-4D0E-42E2-86DC-DEC527DE759C.jpeg?1783777485',
  },
  '0x7f0aBeF0C07280F82c6a08ead09dEd6BAE2C13Fc': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x7f0abef0c07280f82c6a08ead09ded6bae2c13fc.png',
  },
  '0x7f3d6B93809Fd4534Bf3C5B25dEEAeC0aab5a1D8': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174524/small/photo_2026-07-10_20-08-28.jpg?1783858507',
  },
  '0x7Fe3778B2520A5868fB8BC16FEa0f33dd9e7122a': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175390/small/tradepools.png?1786216549',
  },
  '0x7FE995a80075dF3Dc8Ae11A9b82c7FE4202CD87f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174672/small/fmu02lq7zai1iyp4qqwfnmu5wr1v.?1784552285',
  },
  '0x8005d266423c7ea827372c9c864491e5786600ea': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x8005d266423c7ea827372c9c864491e5786600ea.png',
  },
  '0x811624d7a62E5079052A9B4F8Ec0a139Ef389283': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174895/small/y3nffajapygb73m7330p2b5uf5d0.?1785394595',
  },
  '0x822CC93fFD030293E9842c30BBD678F530701867': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x822cc93ffd030293e9842c30bbd678f530701867.png',
  },
  '0x82DA4646242e1D962e96e932269Dc644c94a9CaA': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x82da4646242e1d962e96e932269dc644c94a9caa.png',
  },
  '0x834A24d16Bf56d692C2e5fFF9428f9d01f2f1ca5': {
    logoURI: 'https://loxicoin.com/brand/loxi-icon-48.png',
  },
  '0x834b31164b5e5F4a08B441D796aBB85f714bb7C1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174469/small/49vk4m8lsi2tg3kda41dwkm444fb.?1783760729',
  },
  '0x839b8bd8ED3d2F1be5a709CE99144337296681c7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174663/small/3w1woop8vyyku4w8vw09wxfd4oce.?1784447367',
  },
  '0x83d37C1C2c3ed4E6536A01fD92C2A75453b57cc2': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174427/small/prometheus.jpg?1783669702',
  },
  '0x84aD72f6FD6bcCab5b5aa4F3C9ab86863bD2bCDa': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174426/small/hoodagent.jpg?1783669375',
  },
  '0x84b7515081A7Ac5adc26179b77A8B18A8c6725C0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174486/small/mintly.png?1783767591',
  },
  '0x84F210f9fa42613E5F5bC89EE4978AfBd1e90F11': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174464/small/RH_colored_icon.png?1783705268',
  },
  '0x851BaBFe94E3fFa5a6d9C3c0Dd9f27b7BF0175F6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174874/small/qeb90qeoa1oby1f37nzqe8ru62dt.?1785289079',
  },
  '0x86923f96303D656E4aa86D9d42D1e57ad2023fdC': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x86923f96303d656e4aa86d9d42d1e57ad2023fdc.png',
  },
  '0x86a24426D1FC5dfDEe454120af3ECc3Cc552789b': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174730/small/ow343bvobqvponxu56hfnyguw0wl.?1784703299',
  },
  '0x8750dA3e48345Ec0C5AAAACfcda2A004Da3B60c2': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175273/small/Unifrog_Logo.png?1786151217',
  },
  '0x880B852316d430741C5B693AA53f22871e42eE77': {
    logoURI:
      'https://teal-negative-crocodile-260.mypinata.cloud/ipfs/bafkreidm4ldqawsn2i7mtiqnxw6nlgrumv27ifkqslueie2xg5yfkijxsi',
  },
  '0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x894e1ec2d74ffe5aef8dc8a9e84686accb964f2a.png',
  },
  '0x89776d4Cd68193597A2fC132cfaC1fDe36CCeA8a': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x89776d4cd68193597a2fc132cfac1fde36ccea8a.png',
  },
  '0x8b7dAF8ca650Ab30dF4c686e1E3689E9248732C6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174687/small/boardwalk_avatar_white_on_blue.png?1784621838',
  },
  '0x8baDa99332848483995ef9c61F4bfFcED1baFEED': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174644/small/IMG_0568.jpeg?1784377524',
  },
  '0x8cF07C5A878945185d327aAa6e33FAa95F95e7bF': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x8cf07c5a878945185d327aaa6e33faa95f95e7bf.png',
  },
  '0x8d4dFaaA4198b6486E0293Fec914C2B6a821D4DC': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174287/small/kitsu-logo.jpg?1782940070',
  },
  '0x8e62F281f282686fCa6dCB39288069a93fC23F1c': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174350/small/sOAZF0mL_400x400.jpg?1783654472',
  },
  '0x8e7A9f9817eCf2649c0316b22Fea274D522C7b9B': {
    logoURI:
      'https://assets.coingecko.com/coins/images/66856/small/Vibe3DPurple.png?1750841683',
  },
  '0x8eC17C059f250A5c19566C3fC56EE13A343dD283': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174805/small/e589hufyxhv81u1xhhx9tttbgvlu.?1784970765',
  },
  '0x8ECEA3d0E648DB646d824AA51EedeB16aC3d6878': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174661/small/cuy40m3sqh9boqn7pdlzirdt299x.?1784447111',
  },
  '0x8eD8Ab093d29e9ccBc26BB38Df09910Ae1d69125': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174677/small/wkioabj0q2i25rcbq7f78ok0ybau.?1784553497',
  },
  '0x8eF20885F94e3D9bc7eB3080279188Bd5ED7c08C': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x8ef20885f94e3d9bc7eb3080279188bd5ed7c08c.png',
  },
  '0x8f100e99dDF699320724e37Cb866770381d47382': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174608/small/h6trwdnktfg2o4blsjf3psm2jj7q.?1784190982',
  },
  '0x8f86a15EC17cb3369d8b3E666dAdBC11daA82b79': {
    logoURI:
      'https://assets.coingecko.com/coins/images/24383/small/APECOIN.png?1756551529',
  },
  '0x8fDE2C15D44eB7Cc1A889bc74633e226F91d3295': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174517/small/rhoodies.jpg?1783851136',
  },
  '0x8Ff92566f2e81BDd68EDfAa8cde73942A723796b': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174375/small/vex.jpg?1783487786',
  },
  '0x90079857237dA767c38D1d261a39848ea424319E': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174513/small/9zf8mhbo75icx26z17pr0grkgn41.?1783848877',
  },
  '0x9108f41aE052CA5A096405cf05097bF4f46B738f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174754/small/xmto3qqp9ups76amvxr4fhs5ubk2.?1784783735',
  },
  '0x912136B5Ce6063591e6ae47eDC76cDe98235860E': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174581/small/1000022977.jpg?1784104402',
  },
  '0x91F41b74b7906266d4D28a327EBD0ed86c119261': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175328/small/uohm.webp?1786096339',
  },
  '0x92Ef19E82bD8fF36661DE838D5eaE7e5CEF0EfFE': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x92ef19e82bd8ff36661de838d5eae7e5cef0effe.png',
  },
  '0x92FD66527192E3e61d4DDd13322Aa222DE86F9B5': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x92fd66527192e3e61d4ddd13322aa222de86f9b5.png',
  },
  '0x941AE714EC6D8130c7B75d67160Ca08f1e7d11Dd': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x941ae714ec6d8130c7b75d67160ca08f1e7d11dd.png',
  },
  '0x94FEf3763ED87051267dCd7FfC5DF416B6C03a7E': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174568/small/robinpay_icon.png?1784047831',
  },
  '0x95052ddcd5DC25641657424A8Cf04834997E1730': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x95052ddcd5dc25641657424a8cf04834997e1730.png',
  },
  '0x9516922a56171AB9834b88864d1010a6D8633296': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174841/small/artcoin.png?1785081111',
  },
  '0x9651342CeA770aE9a2969Ba2A52611523146aef9': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x9651342cea770ae9a2969ba2a52611523146aef9.png',
  },
  '0x96765066f6a040a21EB027167D2315B707c82633': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174431/small/ba178407-dda3-4969-a7e3-071cec79c121.png?1783670771',
  },
  '0x970078468807853bC316432E745165eB34398Ba3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174612/small/h2je1zbvqwamnc7nwvl6zs0tgagi.?1784191502',
  },
  '0x9727B500AC8726C716f018E5D3Ca871481245065': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174690/small/logo.png?1784628480',
  },
  '0x97e39393a9aFc4F21b1E74209eE0522E91eF028C': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174635/small/hoodclaw.jpg?1784293778',
  },
  '0x98E75885157C80992A8D41b696D8c9C6Fb30A926': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x98e75885157c80992a8d41b696d8c9c6fb30a926.png',
  },
  '0x99b1887E985a985ECb23AC248421EAc96CB92492': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175235/small/gfd000s543gataterozxani6s5a6.?1785894592',
  },
  '0x9B09c435BC5DA088722bE47E97989fB1e3Ed4eB9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175330/small/the_chosen_frog.webp?1786096998',
  },
  '0x9b23573b156B52565012F5cE02CDF60AFBaa70Be': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x9b23573b156b52565012f5ce02cdf60afbaa70be.png',
  },
  '0x9cA1cC0c90d97B4F36c5E2232d4fbD705a73c65d': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175372/small/kamxnsoze4jsqy51dwkzlg1n6una.?1786160200',
  },
  '0x9d783133a3ff9BA27Fa1605547368CF9a316341E': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174807/small/EQUI_logo.png?1784996283',
  },
  '0x9D9c6684F596F66a64C030B93A886D51Fd4D7931': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0x9d9c6684f596f66a64c030b93a886d51fd4d7931.png',
  },
  '0x9e93EA35Be23Ab0e1E20ed6b62d3b1Cbd5234a83': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174453/small/40c133casfwn37d8vjv1wxezh0ev.?1783691920',
  },
  '0x9fb101579e716B2571aB069c2718cd06b69ffdD7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174489/small/cursor_%288%29.png?1783778079',
  },
  '0x9fbe210007dDd8389f98d0253018e65CC48b9D24': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175269/small/rhLogo.jpg?1786015269',
  },
  '0xA15cD06dD305269A0f48BeBEB30aa3588Fba7b32': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174731/small/mrxvnxar3u7g7ktbuhekb01doafd.?1784703453',
  },
  '0xA2718f80f1FE0CdeC69c9023ee006807dD487a8c': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174349/small/IMG_0860.jpeg?1785231295',
  },
  '0xa3054F28c48b387D4825Be8f3b79eD161ABC5405': {
    logoURI:
      'https://www.geckoterminal.com/_next/image?url=https%3A%2F%2Fcoin-images.coingecko.com%2Fcoins%2Fimages%2F68170%2Flarge%2FIMG_20250811_025232_632.png%3F1754993709&w=128&q=75',
  },
  '0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xa30fa36db767ad9ed3f7a60fc79526fb4d56d344.png',
  },
  '0xA3B9120593C93169E36A0CDea1324584B745E03f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174756/small/starecat.png?1784784071',
  },
  '0xA3BfBccD4Aeec8ac56B17FEE3e02Dd2C60722ccc': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174618/small/cashstrategy.jpg?1784192415',
  },
  '0xa4874f62c8826E19cF8691BCAbd02fe1a0B7401F': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174417/small/oqo9mht01qlu8n2efrerer0k9h5k.?1783666715',
  },
  '0xa4BD8dEF4b887FD1851DEFe10AcdCf7A84437a88': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174288/small/pepewifhood.jpg?1782940593',
  },
  '0xA56605E4c65e702F72830bf6880E821588BAb836': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174463/small/cjt8kdbnqterkghhvvq471lvm2ar.?1783694518',
  },
  '0xa5baC17a919A10Ba0628CDA5BCf273681e1a8D4e': {
    logoURI: 'https://i.postimg.cc/44WSg16J/mystery-48x48.jpg',
  },
  '0xa5D4968421bA94814Be3B136b15cf422101aC1a3': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xa5d4968421ba94814be3b136b15cf422101ac1a3.png',
  },
  '0xA68A46Db0bAa6e23A024c90741ACE041B588c3Ae': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175331/small/hodlbd.webp?1786097265',
  },
  '0xA737dF5De18E3AA6b0bf8C2e9846Ed699F6f2AEB': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174575/small/ponstar.jpg?1784095225',
  },
  '0xa784B82c39C482d3Fbd6cDD93Ccf9a230b09Dfe7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174758/small/photo_2026-07-10_11-49-55.jpg?1784795358',
  },
  '0xa79e6Db2549c541b6CAe25e99021728425b9d0E9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174561/small/frogcat_400x400.jpg?1784019990',
  },
  '0xA80Ba06F0a0327E68dA6BedE67eB35ac023D6e62': {
    logoURI: 'https://thefloor.sh/branding/floor-logo.png',
  },
  '0xA80eb66b3E0CF66ccB46f8b8C9e7ff5803eEb820': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174429/small/Screenshot_2026-07-10_at_6.46.16%E2%80%AFAM.png?1783670272',
  },
  '0xa85Bd69EA5492e42bb912A82B4fEED6fe10D5e12': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175271/small/leak.jpg?1786026303',
  },
  '0xa870f8C7CAE9705194a141b0C2964B6C79ee3742': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174334/small/newfeatherlogo.jpg?1783323012',
  },
  '0xA8eB3BCcbf2017eE7CBfb652eB51CF2E1B153289': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xa8eb3bccbf2017ee7cbfb652eb51cf2e1b153289.png',
  },
  '0xa9038D2c4E798d10dD46c2FDB1f72c9B397bbDAD': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174576/small/j43c4zpw5s1jg5unit79lh9rzw93.?1784095092',
  },
  '0xaA4b6a79Df257E50E0079cD812A92262eE3951b0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174678/small/ags3nzvw7ber00sk0ma6fdcwlyxr.?1784553807',
  },
  '0xAA730F8cca8A22600f92d854322C560390FCff87': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174643/small/delphic.jpg?1784364418',
  },
  '0xaAb3d2E25869DD9661e7A886B9A51c02Ee6c7777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174628/small/623vjbzuafixrvzzka4do5ckxy7k.?1784285002',
  },
  '0xAB26d5B48bD07f1248A66FD817036f785078B51d': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174642/small/uo1z06se7r152mhbgi1yw6byv9l2.?1784364328',
  },
  '0xac0F333bBEBB62B6d16322650641Bd5eF2B849e5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174716/small/1000130024.png?1784664797',
  },
  '0xaC9BBA3f724dFbd6EC677684783D2DE2AAE05ad3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174481/small/zln5ucvnevtmdirtsx0bddi56w8f.?1783767096',
  },
  '0xACe3C5Adc456dE444501D91C12B0b03f902EB250': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174512/small/j634h6sovs0z4f6z5okrtbplk100.?1783848736',
  },
  '0xaCE55FE98Bab14366dD49aB5AA5dF76aA11A3c6f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175197/small/Wojak_on_Robinhood-.png?1785481093',
  },
  '0xAd0c4E4Acc1BA90ad5B28CCdc6F8E7eE35db7777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174840/small/vv3je0tbvnfroocy17fgj998f5np.?1785055621',
  },
  '0xad25Ac6C84D497db898fa1E8387bf6Af3532a1c4': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xad25ac6c84d497db898fa1e8387bf6af3532a1c4.png',
  },
  '0xAd622320e520de39e72d41EF07438C3Fd3354875': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xad622320e520de39e72d41ef07438c3fd3354875.png',
  },
  '0xAd9e5FB798D12663911388A8d25EBa21D6141401': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175327/small/bow.webp?1786096045',
  },
  '0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xaf3d76f1834a1d425780943c99ea8a608f8a93f9.png',
  },
  '0xaF4C10fEf50059d1e3E8aB1C80E46DB6A76098B4': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174671/small/3jkwzwiyv769b9o2cumpl1o5c7ne.?1784551608',
  },
  '0xb0992820E760d836549ba69BC7598b4af75dEE03': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xb0992820e760d836549ba69bc7598b4af75dee03.png',
  },
  '0xB1BF26c1D20ff267A4f93550d1E0d06ac40a114B': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xb1bf26c1d20ff267a4f93550d1e0d06ac40a114b.png',
  },
  '0xB1cB27F78B7335df8C3d8ebF0881A15BeD6BeB60': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174567/small/swood_logo.png?1784046843',
  },
  '0xb1d46EfF0e3D1a4169A4D4159B46c5783b4F7a05': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174526/small/IMG_5018.jpeg?1783868910',
  },
  '0xB2A9A1D670155dEffDFf950985b5B4a587a9b583': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174787/small/Nocturn.jpg?1784875579',
  },
  '0xB358766827d7C704d3c52a57b5Cf181D1b0ffC6c': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175262/small/chwdr.webp?1786008157',
  },
  '0xB47f4702DEB124cb4eB6286bE83c9d84277C6239': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174639/small/3jy9qsd8qu9527llxncb5532ri2c.?1784363001',
  },
  '0xb66D83f0a7EAE1beD80Df1E049a5D6AEFa90eb66': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174421/small/rao8t0ak6a52v8qi0hkpiukjgjxr.?1783667934',
  },
  '0xB6d695d5fbcEbD837f6b9f214c9BeeE8bA90762B': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174813/small/Logo-green.png?1785003828',
  },
  '0xb8DBf92F9741c9ac1c32115E78581f23509916FD': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xb8dbf92f9741c9ac1c32115e78581f23509916fd.png',
  },
  '0xB90A19fF0Af67f7779afF50A882A9CfF42446400': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xb90a19ff0af67f7779aff50a882a9cff42446400.png',
  },
  '0xb9F89a5a075CC280362C5167c5E95723BB2c8caD': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175281/small/inu.png?1786028586',
  },
  '0xBaabCB1800C539a58a46035d3982403a37FD6d5D': {
    logoURI:
      'https://assets.coingecko.com/coins/images/69336/small/logo-128.png?1758225720',
  },
  '0xBbb8Ef3181661512CEAB66e0B213C29211B24b6c': {
    logoURI:
      'https://assets.coingecko.com/coins/images/56006/small/usduc-logo.jpg?1748000956',
  },
  '0xbcA2f7789815d7cf627A60e85f615532efB3BE96': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175272/small/abe.jpg?1786026526',
  },
  '0xbd433ecAB074AE6A740959Fb5e7bf1d02f6F57f6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174477/small/ofg1s8agrx2cejbbfx7ygyydkqsg.?1783762358',
  },
  '0xBD8e0244791B67547b4aE8cFc9463AB19f6e9c08': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174520/small/py0rrrbly1yhyi5kfxgrtkq9hw4e.?1783855214',
  },
  '0xBD957Cc9f1e94617792F37bC40f2F299e78AcF3e': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175270/small/Crude_Cat.jpg?1786019525',
  },
  '0xbE6702d7b70315376dC48a3293f24f0982F86386': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xbe6702d7b70315376dc48a3293f24f0982f86386.png',
  },
  '0xBeC416aC3e36A8CA0571cEf5a104EDAeF2a31A89': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174620/small/pfp.jpg?1784257386',
  },
  '0xBEF75684C43c4ea7BD18Dd532a2244674Ee8b926': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xbef75684c43c4ea7bd18dd532a2244674ee8b926.png',
  },
  '0xbf72347bacEfE747Eaf48b8A66E38BABad3020A0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174286/small/_STONKS_-_COINGECKO.png?1784083271',
  },
  '0xbfc3a980B78B007eF0CDe9625E52dbB66c51A1A7': {
    logoURI:
      'https://assets.coingecko.com/coins/images/32575/small/200.png?1698554742',
  },
  '0xc01aA1fECeC0605b13bc84874ff7256C0f5F562a': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xc01aa1fecec0605b13bc84874ff7256c0f5f562a.png',
  },
  '0xC0b57404486baE3deCd0f47c49406214A303daC8': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174474/small/b80fvpea97rvr3n4dgnfi3phm23h.?1783761692',
  },
  '0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xc0d6457c16cc70d6790dd43521c899c87ce02f35.png',
  },
  '0xc23d7218512c672BA6e87b7F8bccE53355f55931': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174611/small/ksktdldgjag5fe2ync0v0ks5fd5v.?1784191378',
  },
  '0xC35968C7F5475bb03a43C7382526F4118E01C0de': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174634/small/zyadtlnqzwoufadtwxbe4y31s8yv.?1784293650',
  },
  '0xC583c60aeF9Dc401Da72cEC1B404743a93cea1Cc': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xc583c60aef9dc401da72cec1b404743a93cea1cc.png',
  },
  '0xC5aC3b7664bA1ac915145cc58F50b89eC3a2970d': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174674/small/uksja0jisrnu6on2t05gyrqu10x3.?1784552817',
  },
  '0xc6911796042b15d7Fa4F6CDe69e245DdCd3d9c31': {
    logoURI:
      'https://assets.coingecko.com/coins/images/34057/small/LOGOMARK.png?1708356054',
  },
  '0xc72b96e0E48ecd4DC75E1e45396e26300BC39681': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xc72b96e0e48ecd4dc75e1e45396e26300bc39681.png',
  },
  '0xC72c01AAB5f5678dc1d6f5C6d2B417d91D402Ba3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174391/small/telegram-cloud-photo-size-1-5084796264477559962-y.jpg?1783986760',
  },
  '0xc72F232a6869e6CF34dC06129AfFD07F8a2a246A': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175391/small/mancer.jpg?1786259391',
  },
  '0xc79D46D716B33b463b3A6574d6eE26009aBF4E9a': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174515/small/bycocket.jpg?1783850845',
  },
  '0xC9E7C34fa156a235e8B8601171a543bc9c84a1B9': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174729/small/3feil5y7kqcu4kdtw2x05q6gpcel.?1784703134',
  },
  '0xcA0Da673A451C84917d7dd0362109eFFf0f8825A': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174651/small/ebess-bolt-200.png?1784383618',
  },
  '0xCA70d457418b90493E5735De6eC4410C3945498E': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174732/small/20wrx2u04dnf1ihw14v63x271ffq.?1784703535',
  },
  '0xCA9c78Dd337A67F6e0077F65F5E9218719d30eDf': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174712/small/netnet_400x400.jpg?1784646716',
  },
  '0xcBB95BBF36099d34dA091dc6Fa6F49EfA257Cee3': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xcbb95bbf36099d34da091dc6fa6f49efa257cee3.png',
  },
  '0xcC142366735c882F7885d3c747db99e45E13E453': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175422/small/IMG_1462.jpeg?1786297777',
  },
  '0xcC9C1Ec224c3824AE5EA699EC72ef5FAD4165e49': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174890/small/forecast.jpg?1785393826',
  },
  '0xcd1fC623C597C201238686E19985a653238e36AA': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175275/small/pigi.webp?1786027240',
  },
  '0xcDd50D73B45085D71Cb05e2ca238d12C3Bd7bEBD': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174733/small/buttercoin.jpg?1784703709',
  },
  '0xcf6B2D875361be807EAfa57458c80f28521F9333': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xcf6b2d875361be807eafa57458c80f28521f9333.png',
  },
  '0xCF8B02128d2803b3dF114E277094cC1096294b5C': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174544/small/CrashCatRebrand-square-1192.png?1785136368',
  },
  '0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xd0601ce157db5bdc3162bbac2a2c8af5320d9eec.png',
  },
  '0xD1D4BBE54fDEafC83693420c5ADe4A2aBE6A90Da': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174438/small/IMG_4929.jpeg?1783672528',
  },
  '0xD2259fcb0408417ab93a637e1ea357c6FFb7D786': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175231/small/stella_400x400.jpg?1785854334',
  },
  '0xD3D5bE6558F84e628EE091B511Df92b4e461a53b': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175253/small/unipeg.png?1785999773',
  },
  '0xd4052415613B34Af236024B895574c467f65b6dD': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174346/small/4663.jpg?1783360399',
  },
  '0xd554E75f85cB1fCb5B6640B55779D566ac60De9f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175314/small/froggy.png?1786088246',
  },
  '0xD5f3879160bc7c32ebb4dC785F8a4F505888de68': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xd5f3879160bc7c32ebb4dc785f8a4f505888de68.png',
  },
  '0xd69845E0589c8D59dE25E7a885F9dCEcaEC95b69': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174538/small/pip_400x400.png?1783957140',
  },
  '0xD7020736a3B5E3ba7978b6bF922B42f8217dB584': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175326/small/toucan.webp?1786095918',
  },
  '0xD7321801CAae694090694Ff55A9323139F043B88': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174595/small/juggernaut.jpg?1784167487',
  },
  '0xD8d1C08A8bA4fc64BAC744f74290B89ADcb6Bf25': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174514/small/seedcoin.jpg?1783850727',
  },
  '0xd917B029C761D264c6A312BBbcDA868658eF86a6': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xd917b029c761d264c6a312bbbcda868658ef86a6.png',
  },
  '0xDa2a4b23459e9ca88183e990802be644AcA7C4B0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174755/small/f2zm3qdaiefvwx4qq74tkteu7q4p.?1784783826',
  },
  '0xDb0c60375Be0031B2817fd0c9D178bA3a85b6666': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174603/small/b5gdllavnvo7f54wzf406i7oyxqq.?1784189197',
  },
  '0xDB87393727b666c43f5aecB03d8B419bA54D9b03': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174699/small/7t4dl21ciugls2q680q2kew04slp.?1784643462',
  },
  '0xdBE9A8897f73Ee91FC2e1e27F9b50A72f9fE5A43': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175311/small/captainrobinhood.png?1786087008',
  },
  '0xDCa6da2ADcebE397C15f348F6EE38EE0eBe6b867': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174384/small/IMG_2444.jpeg?1783527074',
  },
  '0xdcc34bdD5D3C30237303b95D2F59cc29437b5c74': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174480/small/ihx8i8chu5ellibewxvsz1c5c5sv.?1783767012',
  },
  '0xDdf2266b79abf0B48898959B0ed6E6adf512be74': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xddf2266b79abf0b48898959b0ed6e6adf512be74.png',
  },
  '0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xdf0992e440dd0be65bd8439b609d6d4366bf1cb5.png',
  },
  '0xDf608a65311f36242A5cc5Fa056B9Ae43dB55EA1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175268/small/seal_logo.jpg?1786015029',
  },
  '0xe013e34F03F42d49E836d59CF6353B897c337777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174649/small/new_logo.jpg?1784380868',
  },
  '0xE0444EF8BF4eD74f74FD73686e2ddF4C1c5591E8': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xe0444ef8bf4ed74f74fd73686e2ddf4c1c5591e8.png',
  },
  '0xe0Cc2751249B797871b694AD3779755b7D4b1111': {
    logoURI: 'https://i.ibb.co/XfC1SfQ3/photo-2026-07-13-21-56-27.jpg',
  },
  '0xe15db7C8547A0adD11eB26A700246cCa08aEfCe5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174898/small/7thwbtf3gwr8kknbqmtv10fgaijr.?1785395134',
  },
  '0xE170dC96ca10103E0D4C5d9293C5A3A72Ee365a5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174507/small/logo.png?1783834955',
  },
  '0xE2C24A2394415EA928653f27c74684C95057B13B': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175325/small/rhps.webp?1786095760',
  },
  '0xE44951407D2ed8E73dce4b7002908732BC0d0bC3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174551/small/IMG_0751.jpeg?1784014646',
  },
  '0xE49A1C3033EcC6b804bc423021D3F71F1A3e0F9B': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174351/small/roh_400x400.jpg?1783361275',
  },
  '0xE555853720737512E3f8Ccf64159A087B4Da51db': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174396/small/9i1mvghswnk59rioodi0ewlpqco8.?1783580569',
  },
  '0xE59e2953334cc1664181976D79C4b5d39eAb7777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174657/small/nlxe1a3rglt7xwd04amg12ylvua9.?1784446540',
  },
  '0xE59ECcb15EA07A755eB9587EefdA7929559E1Fa6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174393/small/rflow.jpg?1783580255',
  },
  '0xe6613D2Bbd5f5C5bb203C36eE414ffaA4a47a977': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175201/small/48078.jpg?1785493579',
  },
  '0xE77d354898A44808ff3999947002785CD727BEd5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/13117/small/sfi_red_250px.png?1696512904',
  },
  '0xe81DC008231035C91F09633c541394B9DdF53673': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174483/small/2qbpbp79qyj6a2zjzsxd3zl6pgiy.?1783767232',
  },
  '0xe8c044b717E87Eb583f828a990fd81f761AeDCD0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175312/small/VC.png?1786087260',
  },
  '0xe8fB470E0685437d7739BD2AacBA60b228800335': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174596/small/logo.png?1784184003',
  },
  '0xe93237C50D904957Cf27E7B1133b510C669c2e74': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xe93237c50d904957cf27e7b1133b510c669c2e74.png',
  },
  '0xe934e36A439C94017B64a3FecE66AF12099aBF50': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174654/small/9gwu14e3hpizobkefg65k66l70wu.?1784445702',
  },
  '0xea72Ecca2d0f6bFA1394DBBCff85b52CD4233931': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174169/small/0xea72ecca2d0f6bfa1394dbbcff85b52cd4233931.png?1782444721',
  },
  '0xeaa9abB805Db03b6859662354aBfE0C2A30902ae': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174482/small/v64shru14od043vgkuastg83stim.?1783767178',
  },
  '0xEafA804083A4886a9460b5B19557334A652bEBa8': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174473/small/ig41n6nw5t647mtxdhqxi89s54ym.?1783761466',
  },
  '0xeB30663bDFf0622Ef4e4E5cBb4E975F19f33f51D': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xeb30663bdff0622ef4e4e5cbb4e975f19f33f51d.png',
  },
  '0xec262a75e413fAfD0dF80480274532C79D42da09': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xec262a75e413fafd0df80480274532c79d42da09.png',
  },
  '0xec51B6E5D99487Ac5646F3311C109714b54f6ED8': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174543/small/cgy1jwn1e4c0jvga6xm9mun1rfg1.?1783957800',
  },
  '0xEDc62851Ef24928D934024f69bB073A305090663': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175215/small/yeg2neshdmbhbdrghdxozgo77kzr.?1785656466',
  },
  '0xef0A84b16902EFCD41Fa001Bd6473c64876B93b0': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175277/small/1life.webp?1786027773',
  },
  '0xF0568863195770965a6D8abb0aa87F4314b80320': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174710/small/slippy_400x400.jpg?1784646272',
  },
  '0xF0AB0c93bE6F41369d302e55db1A96b3c430212D': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xf0ab0c93be6f41369d302e55db1a96b3c430212d.png',
  },
  '0xF0C4BF4C582cb3836e98394b1d4e7B7281101bE8': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xf0c4bf4c582cb3836e98394b1d4e7b7281101be8.png',
  },
  '0xf0E17e54239CD945Cd7bEa471a3a2CA6a8C7f7A3': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174850/small/lemonofficiallogo.jpg?1785087164',
  },
  '0xF11168Ec379EfD20a35006f1D44Cc5F9e4E94e67': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174795/small/epjr5bp1jx8di81aa5yyhglyqgvj.?1784883172',
  },
  '0xF132Bd1D1770D42CF4Ec8659b9077D0d1c197CC1': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174478/small/b7uzk8j65odkho6ldjmy4a0yb7vy.?1783762549',
  },
  '0xf172dC5b774C52432E1E5223cD30f8e8A1096969': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175384/small/IMG_9217.jpeg?1786208691',
  },
  '0xf1953DAB6FaD537488d5A022361FfAa8B4c95eC6': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xf1953dab6fad537488d5a022361ffaa8b4c95ec6.png',
  },
  '0xf202dE51BB42A0073948b0971707D14C54Ef5F44': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174737/small/IMG_5333.jpeg?1784707626',
  },
  '0xf23250dac154D05Bb671CB0d0eBEf3c635c79CE2': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xf23250dac154d05bb671cb0d0ebef3c635c79ce2.png',
  },
  '0xf2915d1e3C1B0c769d0c756Ec43F1c1f6c99cD03': {
    logoURI: 'https://af-pp-inverted-copy.tiiny.site/AF-PP-Inverted-copy.svg',
  },
  '0xf314AEDeAaDCB02F33a13Eae471Fe06D13AA7777': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174415/small/hyk32wnnk1jtgu2hftwgscdt9e3v.?1783666304',
  },
  '0xF444F3C77C77a33F7c8d8fcab8a1E88aFb843dA5': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174624/small/qj9v3lb8qibwfwrdkdx3ayj7avvh.?1784278227',
  },
  '0xf44702b17d9abD53815F703e772F35E9c71A53af': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174343/small/tljlld1hjqbs8rz1f0hdznr8ouls.?1783332390',
  },
  '0xF4C450c1570C2DBda91DE1Ed2E39995a15028c97': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174373/small/4un2w5gi4dfttub6y5hianoyvffa.?1783486971',
  },
  '0xF53F66751B1Eff985311b693531E3290F600c410': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xf53f66751b1eff985311b693531e3290f600c410.png',
  },
  '0xf55F03Ea76c4e21F263631b1860b55E255ACb339': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174458/small/mog.jpg?1783693336',
  },
  '0xF82119ebd01eb6AB67105C9536A713D61a25cf9f': {
    logoURI:
      'https://assets.coingecko.com/coins/images/847/small/token.png?1775296339',
  },
  '0xF8BC08092C06dB6148114DCf82AF881F1085f92b': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174574/small/4vvnmslrns3stkpsmbsnsv4cu5ae.?1784094690',
  },
  '0xf9B46d3D1B22199D4D1025a9cEDB540A33F1a2d5': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xf9b46d3d1b22199d4d1025a9cedb540a33f1a2d5.png',
  },
  '0xfB1bcB6817F7b8fA86896D3253b16aEB7Bd6A5A8': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174519/small/worth.jpg?1783855128',
  },
  '0xfB4729659eeF22Bfc1c2B680F6F873f8147aaaab': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174386/small/robin-mascot-circle.png?1784168000',
  },
  '0xfB60FA2dB6A8C6e7D510aD33551DeFAE89A917BB': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175196/small/IMG_0978.jpeg?1785480888',
  },
  '0xfB97e1CA99378eA348Eb794cbed099408ca74D1C': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174904/small/marketcat.png?1785397060',
  },
  '0xFbD1Bf9d354CD8197Ab54f80778C03cc468ADAaf': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174423/small/wfzc0l3rb6j0rhrmvf23peh9ha5m.?1783668573',
  },
  '0xFc39e99e78524d7c891669F70d5aa92aB1041eb6': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175254/small/hdcb8aaghz9urr1l9ip0kpl203sh.?1785999863',
  },
  '0xfD181632e1F2335DaB74535E6dD29082d3191bb2': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175266/small/rflix-logo.png?1786014133',
  },
  '0xFe2112b4569D3a131E7964dCF45c155d7907534e': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102174505/small/template_copy.PNG?1783814065',
  },
  '0xfEACeF09BE172634Bd8CADc2429b92EB4ed73799': {
    logoURI:
      'https://assets.coingecko.com/coins/images/102175276/small/unicorn.webp?1786027607',
  },
  '0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD': {
    logoURI:
      'https://cdn.robinhood.com/ncw_assets/logos/0xff080c8ce2e5feadaca0da81314ae59d232d4afd.png',
  },
}

export default assets
