// Auto-generated by `npm run robinhood:sync`. Do not edit by hand.
// Source: https://robinhoodchain.blockscout.com/api/v2/tokens/
//
// Logo URLs only. Lower priority than the RHJ asset data, so this mainly
// supplies icons for non-equity tokens added via tokens/manual.ts.

import { TokenInfo } from '@uniswap/token-lists'

const assets: Record<string, Partial<TokenInfo>> = {}

export default assets
