import * as fs from 'fs'
import { getAddress } from 'ethers'
import { Network } from '../../types'

const MANUAL_TOKENS_PATH = './src/tokenlists/robinhood/tokens/manual.ts'

/** Maps a config name ("hyperevm") to its Network enum key ("HyperEVM"). */
function resolveNetworkKey(network: string): string {
  const key = Object.keys(Network).find(
    (name) => name.toLowerCase() === network.toLowerCase()
  )
  if (!key) throw Error(`Unknown network: ${network}`)
  return key
}

/**
 * Inserts a token address into the manual token list, under the given network.
 *
 * Writes to tokens/manual.ts rather than tokens/robinhood.ts, because the
 * latter is regenerated by `npm run robinhood:sync`.
 */
export function allowListToken({
  network,
  tokenAddress,
  tokenSymbol = '',
}: Record<string, string>) {
  const fileContent = fs.readFileSync(MANUAL_TOKENS_PATH, 'utf-8')
  const address = getAddress(tokenAddress)
  const networkKey = resolveNetworkKey(network)

  // Match the array body belonging to this network's key.
  const regex = new RegExp(
    `(\\[Network\\.${networkKey}\\]:\\s*\\[)([\\s\\S]*?)(\\n\\s*\\],)`
  )
  const match = fileContent.match(regex)

  if (!match) {
    throw Error(
      `Network ${networkKey} not found in ${MANUAL_TOKENS_PATH}. ` +
        `Add a "[Network.${networkKey}]: []," entry first.`
    )
  }

  const [, , arrayContent] = match

  if (arrayContent.toLowerCase().includes(address.toLowerCase())) {
    console.log(`${address} is already allowlisted`)
    return
  }

  let entry = `\n    '${address}',`
  if (tokenSymbol) entry += ` // ${tokenSymbol}`

  // Callback form so `$` in the matched content is not treated as a
  // replacement pattern.
  const updatedContent = fileContent.replace(
    regex,
    (_match, opening, body, closing) => `${opening}${body}${entry}${closing}`
  )

  fs.writeFileSync(MANUAL_TOKENS_PATH, updatedContent)

  console.log(`💾 ${address} added to ${networkKey} in manual.ts`)
}
