/**
 * Syncs the Robinhood tokenized-equity list from the public RHJ assets API.
 *
 * 1. Fetches https://api.robinhood.com/rhj/assets
 * 2. Keeps active assets with a deployment on Robinhood Chain.
 * 3. Writes the checksummed addresses to tokens/robinhood.ts
 * 4. Writes name/symbol/decimals/logoURI to assets/robinhood.ts, which
 *    overwrites.ts spreads in as top-priority metadata for the generator.
 *
 * Example usage:
 * npm run robinhood:sync
 */

import fs from 'fs'
import path from 'path'
import chalk from 'chalk'
import { getAddress, isAddress } from 'ethers'
import { Network } from '../../types'

const ASSETS_URL = 'https://api.robinhood.com/rhj/assets'
const ACTIVE_STATUS = 'ASSET_STATUS_ACTIVE'
const CHAIN_ID = Number(Network.Robinhood)

const tokenlistPath = path.resolve(__dirname, '../../tokenlists/robinhood')
const tokensFile = path.resolve(tokenlistPath, 'tokens/robinhood.ts')
const assetsFile = path.resolve(tokenlistPath, 'assets/robinhood.ts')

interface RhjDeployment {
  contractAddress: string
  chainId: number
  networkName: string
}

interface RhjAsset {
  id: string
  tokenSymbol: string
  tokenName: string
  tokenDecimals: number
  status: string
  logoUrl?: string
  deployments: RhjDeployment[]
}

interface RhjAssetsResponse {
  assets: RhjAsset[]
}

interface RobinhoodToken {
  address: string
  name: string
  symbol: string
  decimals: number
  logoURI?: string
}

// prettier ships no type declarations on v2, so require it with a local shape.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const prettier = require('prettier') as {
  format(source: string, options: Record<string, unknown>): string
  resolveConfig: { sync(filepath: string): Record<string, unknown> | null }
}

/** Format generated source with the repo's prettier config so it passes lint. */
function format(source: string, filepath: string): string {
  const options = prettier.resolveConfig.sync(filepath) ?? {}
  return prettier.format(source, { ...options, filepath })
}

async function fetchAssets(): Promise<RhjAsset[]> {
  const response = await fetch(ASSETS_URL, {
    headers: { accept: 'application/json' },
  })

  if (!response.ok) {
    throw new Error(
      `Robinhood assets API error: ${response.status} ${response.statusText}`
    )
  }

  const data = (await response.json()) as RhjAssetsResponse

  if (!Array.isArray(data?.assets)) {
    throw new Error('Unexpected Robinhood assets API response shape')
  }

  return data.assets
}

function toTokens(assets: RhjAsset[]): RobinhoodToken[] {
  const tokens: RobinhoodToken[] = []
  const seen = new Set<string>()

  for (const asset of assets) {
    if (asset.status !== ACTIVE_STATUS) {
      console.log(chalk.dim(`Skipping ${asset.tokenSymbol}: ${asset.status}`))
      continue
    }

    const deployment = asset.deployments?.find(
      (item) => item.chainId === CHAIN_ID
    )
    if (!deployment) {
      console.log(
        chalk.dim(
          `Skipping ${asset.tokenSymbol}: no chain ${CHAIN_ID} deployment`
        )
      )
      continue
    }

    if (!isAddress(deployment.contractAddress)) {
      console.warn(
        chalk.yellow(
          `Skipping ${asset.tokenSymbol}: invalid address ${deployment.contractAddress}`
        )
      )
      continue
    }

    const address = getAddress(deployment.contractAddress)
    if (seen.has(address)) {
      console.warn(chalk.yellow(`Skipping duplicate address: ${address}`))
      continue
    }
    seen.add(address)

    tokens.push({
      address,
      name: asset.tokenName,
      symbol: asset.tokenSymbol,
      decimals: Number(asset.tokenDecimals),
      logoURI: asset.logoUrl || undefined,
    })
  }

  // Sort by symbol so regenerating produces stable diffs.
  return tokens.sort((a, b) => a.symbol.localeCompare(b.symbol))
}

function buildTokensFile(tokens: RobinhoodToken[]): string {
  const lines = tokens.map(
    (token) => `  '${token.address}', // ${token.symbol}`
  )

  return [
    '// Auto-generated by `npm run robinhood:sync`. Do not edit by hand.',
    `// Source: ${ASSETS_URL}`,
    '',
    'export default [',
    ...lines,
    ']',
    '',
  ].join('\n')
}

function buildAssetsFile(tokens: RobinhoodToken[]): string {
  const entries = tokens.map((token) => {
    const fields = [
      `    name: ${JSON.stringify(token.name)},`,
      `    symbol: ${JSON.stringify(token.symbol)},`,
      `    decimals: ${token.decimals},`,
    ]
    if (token.logoURI) {
      fields.push(`    logoURI: ${JSON.stringify(token.logoURI)},`)
    }
    return [`  '${token.address}': {`, ...fields, '  },'].join('\n')
  })

  return [
    '// Auto-generated by `npm run robinhood:sync`. Do not edit by hand.',
    `// Source: ${ASSETS_URL}`,
    '',
    "import { TokenInfo } from '@uniswap/token-lists'",
    '',
    'const assets: Record<string, Partial<TokenInfo>> = {',
    ...entries,
    '}',
    '',
    'export default assets',
    '',
  ].join('\n')
}

async function run() {
  console.log(chalk.cyan(`Fetching Robinhood assets from ${ASSETS_URL}`))
  const assets = await fetchAssets()
  console.log(chalk.dim(`Received ${assets.length} assets`))

  const tokens = toTokens(assets)
  if (!tokens.length) {
    throw new Error('No usable Robinhood assets returned; refusing to write')
  }

  fs.writeFileSync(tokensFile, format(buildTokensFile(tokens), tokensFile))
  fs.writeFileSync(assetsFile, format(buildAssetsFile(tokens), assetsFile))

  const withLogos = tokens.filter((token) => token.logoURI).length
  console.log(
    chalk.green(
      `Wrote ${tokens.length} tokens (${withLogos} with logos) to ` +
        'src/tokenlists/robinhood/'
    )
  )
  console.log(chalk.dim('Run `npm run generate` to rebuild the tokenlist.'))
}

;(async () => {
  try {
    await run()
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
})()
